stages:
    - test
    - cache
    - build

git_leaks:
    stage: test
    image:
        name: zricethezav/gitleaks
        entrypoint: [""]
    script:
        - gitleaks detect --verbose --source . -f json -r gitleaks.json
    allow_failure: true
    artifacts:
        when: always
        paths:
            - gitleaks.json
semgrep_test:
    stage: test
    image: returntocorp/semgrep
    variables:
        SEMGREP_RULES: p/javascript
    script:
        - semgrep ci --json --output semgrep.json
    artifacts:
        when: always
        paths:
            - semgrep.json
    allow_failure: true

create_cache:
    image: node:18-bullseye
    stage: cache
    script:
        - yarn install
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
            - yarn.lock
            - .yarn
        policy: pull-push


#yarn_test:
    #image: node:18-bullseye
   # stage: test
   # script:
      #  - yarn install
      # - yarn test
#build_stage:
   # stage: build
   # image: docker:24
  #  services:
     #   - docker:24-dind
   # before_script:
     #   - docker login -u $register_user -p $register_pass
    #script:
    #    - docker build -t moatazdevops/demo-app:juiceshop-1.1 .
     #   - docker push moatazdevops/demo-app:juiceshop-1.1
    